name: deploy - weather notifications service

permissions:
  contents: write  # Allows pushing changes to the repository

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GHCR_REPO_NOTIFICATIONS }}:${{ github.sha }} .
          # Tagging image with commit hash using github.sha

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GHCR_REPO_NOTIFICATIONS }}:${{ github.sha }}
          # Pushing the image with commit hash as the tag

      - name: Update Helm chart with new image tag using yq
        run: |
          echo "GITHUB_WORKSPACE is: ${{ github.workspace }}"
          echo "Listing files in ${{ github.workspace }}"
          ls ${{ github.workspace }}
          echo "Listing files in ${{ github.workspace }}/charts"
          ls ${{ github.workspace }}/charts
          echo "Listing files in ${{ github.workspace }}/charts/weather-notifications-service"
          ls ${{ github.workspace }}/charts/weather-notifications-service
          yq eval '.image.tag = strenv(GITHUB_SHA)' -i ${{ github.workspace }}/charts/weather-notifications-service/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git add ${{ github.workspace }}/charts/weather-notifications-service/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.GHCR_PASSWORD }}@github.com/${{ github.repository }}.git HEAD:master
