name: deploy - weather notifications service

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GHCR_REPO_NOTIFICATIONS }}:${{ github.sha }} .
          # Tagging image with commit hash using github.sha

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GHCR_REPO_NOTIFICATIONS }}:${{ github.sha }}
          # Pushing the image with commit hash as the tag

      - name: Update Helm chart with new image tag
        run: |
            sed -i 's|tag: "latest"|tag: "${{ github.sha }}"|g' ./charts/weather-notifications-service/values.yaml
      - name: Commit and push updated deployment YAML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ./charts/weather-notifications-service/templates/notifications-service-deployment.yml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
